paths:
  uploads: uploads
  dam_uploads: ''
  static: ''
  dam_static: ''
  collections: ''
  data: _data
  layouts: _layouts
  includes: _includes
  includes: _bible
collections_config:
  data:
    path: _data
    output: false
    icon: notes
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  posts:
    path: _posts
    output: true
    icon: notes
    create:
      path: >-
        [relative_base_path]/{date|year}-{date|month}-{date|day}-{title|slugify}.[ext]
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  pages:
    path: ''
    output: true
    filter: strict
    icon: notes
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  authors:
    path: _authors
    output: true
    icon: notes
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  category:
    path: _category
    output: true
    icon: notes
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  bible:
    path: _bible
    output: true
    icon: notes
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
_inputs:
  categories:
    type: multiselect
    options:
      allow_create: true
      empty_type: array
    cascade: true
  tags:
    type: multiselect
    options:
      allow_create: true
      empty_type: array
    cascade: true
  notes:
    type: textarea
  transcript:
    type: textarea
  podcast:
    type: textarea
  image_thumb:
    type: image
  image_wide:
    type: image
  type:
    type: select
    options:
      values:
        - Old Testament
        - New Testament
        - Deuterocanonical
  layout:
    hidden: true
_select_data:
  logo_image:
    dark:
    light:
  disqus:
    shortname:
  footer:
    copyright: >-
  navbar_primary:
    sticky: true
    social: true
    search: true
  social_share:
    twitter: true
    facebook: true
    linkedin: true
    pinterest: true
    reddit: true
    tiktok: true
    x: true
  social_networks:
    email:
    website:
    facebook:
    flickr:
    dribbble:
    github:
    reddit:
    instagram: https://www.instagram.com/hopemindfulness/
    linkedin:
    pinterest:
    x: https://x.com/hopemindfulness
    tiktok: https://www.tiktok.com/@hopemindfulness
    vimeo:
    youtube: https://www.youtube.com/@hopemindfulness
  strings:
    author_by: By
  sass:
    style: compressed
_structures: {}
_editables: {}
data_config: {}
timezone: Etc/UTC
